### ISSUE TITLE
How to generate labels to conduct behavior prediction

### ISSUE THREAD

**Issue by shinu335** [GAMMA-UMD/METEOR#3]
Thank you for your wonderful dataset!

I have been doing research based on your dataset. Recently I aim at creating a behavior predicting model. 
According to your README instructions, a label txt should be used for training:

https://github.com/GAMMA-UMD/METEOR/blob/df1ac136d63c584d41b313de06b095efeac45ba8/Scripts/configs/tsn_config.py#L13

Could you provide methods of generating label txt for training, validation and testing?

Yours sincerely

**Comment by MridulMahajan44** [comment]
Hi @shinu335, you should follow the dataset preparation instructions mentioned in the README. The third step produces the annotation files required for the configs.

**Comment by rohanchandra30** [comment]
Closing this out. Feel free to reach out if you have further questions !
